#set page(
  paper: "a4",
  margin: (x: 22mm, y: 20mm),
  footer: context align(center, [Page #counter(page).display("1")]),
)
#set text(lang: "en", region: "GB", size: 10.5pt)
#set par(justify: true)
#set heading(numbering: "1.")

#let kind = sys.inputs.at("kind", default: "")

#if kind == "witness_statement" [
  = Witness Statement

  *Court:* Synthetic Civil Court  \
  *Claim:* SYN-001  \
  *Witness:* Alex Example  \
  *Statement:* First synthetic statement

  1. I am Alex Example. This statement is synthetic and exists only to test document-generation and bundle controls.

  2. The facts in this paragraph are stated from my own synthetic knowledge for this technical rehearsal.

  3. The following proposition is stated on information and belief: the synthetic document register contains five procedural document families. The source is the synthetic exhibit register.

  4. No proposition concerns a real person, real dispute, live evidence or R59.

  *STATEMENT OF TRUTH - SIGNING GATE NOT ACTIVATED IN THIS SYNTHETIC REHEARSAL.*
] else if kind == "exhibit_and_index_material" [
  = Exhibit and Index Material

  == Contents

  - Synthetic exhibit register
  - Synthetic adverse material entry

  == Exhibit Register

  #table(
    columns: (20%, 50%, 30%),
    inset: 5pt,
    stroke: 0.5pt,
    [*ID*], [*Synthetic document*], [*Purpose*],
    [SYN-A1], [Synthetic notice], [Tests exhibit cross-reference],
    [SYN-A2], [Synthetic chronology], [Tests issue-led navigation],
    [SYN-A3], [Synthetic adverse note], [Tests adverse-material visibility],
  )
] else if kind == "participation_and_adjustment_request" [
  = Participation / Adjustments Request

  *Barrier:* Synthetic communication-processing barrier.  \
  *Effect:* Longer spoken exchanges reduce the quality of synthetic participation.  \
  *Measure requested:* Written agenda and written questions in advance where directed.  \
  *Why proportionate:* The measure is limited to the synthetic barrier.  \
  *Fallback:* Short breaks and written confirmation of disputed points.

  This request is synthetic. It contains no diagnosis, medical evidence or live personal information.
] else if kind == "authorities_sheet" [
  = Authorities / Currentness Sheet

  #table(
    columns: (12%, 48%, 40%),
    inset: 5pt,
    stroke: 0.5pt,
    [*No.*], [*Authority family*], [*Control*],
    [1], [CPR Part 32 / PD32], [Recheck official source before filing],
    [2], [CPR Part 22], [Recheck statement-of-truth wording],
    [3], [PD1A], [Participation control],
    [4], [Judiciary e-bundle guidance], [Bundle-format control],
  )
] else if kind == "filing_and_service_receipt" [
  = Filing / Service Receipt

  *Status:* SYNTHETIC / NOT FILED / NOT SERVED  \
  *Filename:* synthetic_filing_and_service_receipt.pdf  \
  *Hash:* generated by the local qualification runner  \
  *Destination:* none  \
  *Portal reference:* none

  A locally generated file is not described as filed or served merely because it exists.

  == Hostile / Adverse Gate

  - Synthetic adverse material is identified and indexed.
  - Information-and-belief sourcing is explicit.
  - No private or live source is included.
  - No signed statement of truth is inserted.
] else {
  panic("unsupported synthetic procedural document kind")
}
